### PR TITLE
Sidebar / a11y zoom / smallscreen / mobile / tablet

### PR DESCRIPTION
**Pull request by illume**
# Makes Headlamp more responsive

- zoom + 400% seems to work (task of https://github.com/kinvolk/headlamp/issues/245)
- More usable with mobile, and tablet sized browsers
- App has been broken up in smaller components

Apart from the side bar also the tab navigation, various dialogs and SimpleTable is responsive.

## How to use

Try using at +400% zoom
Try using in a mobile, and tablet views

## Testing done

Tested loading with different sizes and using the website.
Tested zooming to different sizes and using it.

## Screenshots 

- Zoom 400%
- xs (mobile)
- medium (tablet)

### Zoom 400%

You can see here that it uses the xs (mobile) views when zoomed in so much.

Screenshot 2021-08-04 at 16 44 37
Screenshot 2021-08-04 at 16 44 47

### xs (mobile size) view

Note the table can be scrolled around, and there is a toolbar menu as well.

The headlamp icon on the left opens the side bar drawer (see below).

Screenshot 2021-08-04 at 16 33 12

### xs (mobile size) view temporary drawer open for side bar

Screenshot 2021-08-04 at 16 33 20

### medium (Tablet sized view)

Note the tab navigation is all fitting within the screen and there are arrows to use the extra tabs.

Screenshot 2021-08-04 at 16 39 11
Screenshot 2021-08-04 at 16 39 04

### Future work

The loading screens on mobile view could be improved, but they are usable... so probably will address in another PR another time.

Note: Mostly tested with chrome/ff responsive testing tools... not with real mobile devices. So there are probably minor issues on some devices.

Only one extra storybook set of stories was made which was useful for testing a component. The other extracted components from the big App.tsx didn't get extra stories added in this PR.

### CODE REVIEW

**Comment by joaquimrocha** [comment]
Hi @illume . Nice work, I like how you reduced the sidebar to a single icon/button on small screens.
Here are two issues I think should be fixed before merging:
1. Some dialogs close immediately after opening; this seems to happen when the dialog is initiated from the sidebar on "phone mode", i.e. seems to be related with the sidebar getting closed. I tried to record a gif but my gif app is already in Feierabend. But choosing any aspect ratio where the sidebar is hidden by default and clicking in the + icon or the version button will reproduce this for me.
2. I think some dialogs should be [full screen](https://material-ui.com/components/dialogs/#responsive-full-screen) when on small screens. I'd say that any dialog that occupies >50% of the screen on small devices should be made fullscreen in that resolution. Fullscreen should help with cases like this a bit:
Screenshot from 2021-08-06 11-45-27

As you noted, the cluster chooser dialog looks very broken but we have to redesign it anyway because it looks bad if there are more than 3 clusters available. (And this should be a different PR)

**Comment by illume** [comment]
@joaquimrocha thanks for having a look! I'll have a look at these issues.

**Comment by illume** [comment]
- The links to dialogs at the bottom of the sidebar do not close the drawer anymore.
- All dialogs have been fixed on small view, and the editor one made full screen.
- labels were made to text wrap so they don't grow outside of the grid (in small views especially)

Screenies below...

Screenshot 2021-08-10 at 08 29 00
Screenshot 2021-08-10 at 08 28 51
Screenshot 2021-08-10 at 08 27 42



Screenshot 2021-08-10 at 08 30 35
Screenshot 2021-08-10 at 08 30 16

**Review by joaquimrocha — COMMENTED** [review]
Left a couple of nitpicks and tested again this morning.
Great work and thanks for addressing the cluster chooser views too. It all looks much nicer on smaller screens.

**Comment by illume** [comment]
Put in fixes for those comments, and rebased on main.

**Pull request merged**
