### PR TITLE
frontend: Don't wrap header cells by default

### PR DESCRIPTION
**Pull request by joaquimrocha**
Otherwise the sort buttons are sometimes shown in the next line and
make the UI look very quirky.

### CODE REVIEW

**Comment by illume** [comment]
Can we make this more specific to the sort buttons? Because no wrapping with long headers could be a problem on low width views (mobile/etc).

**Comment by joaquimrocha** [comment]
> Can we make this more specific to the sort buttons? Because no wrapping with long headers could be a problem on low width views (mobile/etc).

Do you mean only not wrapping if there's a sort button?

**Review by ashu8912 — APPROVED** [review]
LGTM!!

**Comment by joaquimrocha** [comment]
This may be riskier than it seems for some users if we put it out so close to the release. Let's park it for now till the next release and see if @illume has a solution.

**Pull request closed without merging**
