### PR TITLE
frontend: Fix unexpected scroll on filter change

### PR DESCRIPTION
**Pull request by yolossn**
Before:

https://user-images.githubusercontent.com/22731013/196707719-c14c87de-b21b-488b-9653-d4ed74f7180e.mp4

After:

https://user-images.githubusercontent.com/22731013/196707641-e2089d51-3d93-4aec-a8c0-b7dcb1be3f6b.mp4

### CODE REVIEW

**Comment by ashu8912** [comment]
@joaquimrocha @yolossn what was the issue here?? Why would it scroll, sorry i tried to understand this from the PR changes but couldn't understand the scroll behaviour

**Comment by joaquimrocha** [comment]
I believe it's something that has to do with focus or loss of it, but in any case, the current solution is good and innocent enough that it shouldn't be risky to add it.

**Review by illume — APPROVED** [review]
Works for me.

I did spot a separate bug on the Cluster view. It doesn't search the Type field. So if I type in "Pod" it fails to find any results. If you don't fix it in here, I'll raise another bug.

**Comment by joaquimrocha** [comment]
> I did spot a separate bug on the Cluster view. It doesn't search the Type field. So if I type in "Pod" it fails to find any results. If you don't fix it in here, I'll raise another bug.

Let's do a separate PR.

**Pull request merged**
