### PR TITLE
headlamp-plugin: Make the package arg of the build command optional

### PR DESCRIPTION
**Pull request by joaquimrocha**
We rely on just calling the "headlamp-plugin build" command without
any arguments, but the build command expected a positional argument as
required, so the default and advised case for building plugins was
failing.

### CODE REVIEW

**Comment by illume** [comment]
interestingly, the CI found a bug when using npm 7. Where npm 7 gets into a loop resolving dependencies, and keeps processing until it runs out of memory. See https://github.com/npm/cli/issues/3359 and https://github.com/npm/cli/issues/3208

There's a work around for running it on CI with npm 7, but users of npm 7 will encounter this bug.

I tried updating the plugin dependencies, and still get the issue. There's another work around or two to try(which I will do next)... but ultimately the bug in npm 7 needs fixing (or maybe it's a bug in one of the dependencies).

**Comment by illume** [comment]
Adding a package-lock.json generated with npm v6 to the template lets npm v7 work.

**Review by illume — APPROVED** [review]
👍 🎉

**Comment by illume** [comment]
Probably we should release a new `@kinvolk/headlamp-plugin` version.

**Review by ashu8912 — APPROVED** [review]

**Review by joaquimrocha — COMMENTED** [review]
@illume , It all LGTM. The only thing I noticed is that we're not testing the `headlamp-plugin build` (no argument) which is what failed initially, or maybe I missed it?

**Comment by illume** [comment]
@joaquimrocha yeah. It's not directly calling `headlamp-plugin build`... but it does so through `npm run build` which calls that. I'll update the test to call `headlamp-plugin build` with no argument directly.

**Comment by illume** [comment]
The `headlamp-plugin build` is tested better now, and also added a test for `headlamp-plugin extract`.

**Review by joaquimrocha — COMMENTED** [review]
Thanks!

**Pull request merged**
