### PR TITLE
Fix unused variables found, use new @kinvolk/eslint-config, update some deps

### PR DESCRIPTION
**Pull request by illume**
- [x] fix unused variables
- [x] update to kinvolk/eslint-config 0.5.0. See https://github.com/kinvolk/eslint-config/pull/9
- [x] update eslint/typescript/prettier related dependencies
- [x] fix `npm run format` prettier doesn't like "`src/`" but finds "`src`" to be most agreeable

### CODE REVIEW

**Review by ashu8912 — COMMENTED** [review]
I think this commit should be the first one and than applying the formatting in a seperate commit

**Review by ashu8912 — COMMENTED** [review]
This also includes changes formatting changes

**Comment by illume** [comment]
Good point, will fix. Thanks!

**Review by joaquimrocha — APPROVED** [review]

**Comment by joaquimrocha** [comment]
I agree with Ashu. Otherwise LGTM. Please merge once fixed.

**Pull request merged**
