### PR TITLE
Storybook, start adding stories for frontend development

### PR DESCRIPTION
**Pull request by illume**
# Storybook, start adding stories for frontend development

Basic .storybook configuration, and some stories using https://storybook.js.org/ for:

- Chart
- Dialog
- SimpleTable
- Tab
- Label
- AuthToken

# How to use

```bash
cd frontend
yarn install
yarn storybook
```

# Testing done

Screenshot 2021-01-11 at 18 58 25

### CODE REVIEW

**Comment by joaquimrocha** [comment]
Linter is failing.

**Comment by ashu8912** [comment]
@illume @joaquimrocha are we like completing the entire storybook implementation in this pr or do we just want the initial setup with basic implementation for now??

**Comment by illume** [comment]
I'd only planned to do these ones in this PR.

**Comment by joaquimrocha** [comment]
> I'd only planned to do these ones in this PR.

That's fine. Let's do the rest later.

**Comment by joaquimrocha** [comment]
I will hold back on this one till after the release, as there are substantial changes to the Auth components in the last commit.

**Comment by joaquimrocha** [comment]
Merging now that we released 0.2.0.

**Pull request merged**
